### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by mdelprin** [toggledbits/DeusExMachina#1]
Please add some form of an on/off to the  app to allow for programmatic enabling/disabling the device.

I would like to be able to enable the vacation timer device using a scene triggered by a google calendar  event device. If the calendar has the appropriate type of event, it will set my thermostat to appropriate settings and enable the vacation timer.

Otherwise, great app!

**Comment by jacksonj04** [comment]
:+1:, I'd love to be able to include this in scenes and modes without needing to manually enable or disable it.

**Comment by toggledbits** [comment]
Everyone, the original author of this plugin has recently passed the repository on to me, and I'll be providing ongong support. There's an active branch right now with some bug fixes that I'm testing for an update/re-launch soon.

In the short term, you can use Lua to enable/disable the current (v1.1) version of this plugin like this:

luup.call_action("urn:com-futzle:DeusExMachina1", "SetEnabled", { NewEnabledValue="1" }, deviceid)

Obviously change the "1" to a "0" if you want to disable. The update will include the ability to trigger scenes when the enable state changes, and set enable/disable in a scene without needing Lua.
