### ISSUE TITLE
Enhancements to only allow 1 light on at a time

### ISSUE THREAD

**Issue by btsterli** [toggledbits/DeusExMachina#15]
Thank you for providing this plugin!  It's very handy and very easy to use.

In the spirit of saving energy, I think a neat option would be to allow the user to specify how many lights are allowed to be on at the same time.  If the user specified '1' for example, then if a light was about to be turned on because its random toggle time came up, it simply wouldn't turn on if at least one other light was already active.

**Comment by toggledbits** [comment]
I've had a few people ask for this. Makes good sense. I'll add it.

**Comment by btsterli** [comment]
That would be great! Thank you. I'm also very interested in the other request I saw for ability to specify dimmer brightness percentage when you get a chance.

**Comment by toggledbits** [comment]
That's in, too!

⁣--Patrick (mobile) ​
