### ISSUE TITLE
Not honoring modes

### ISSUE THREAD

**Issue by brgerig** [toggledbits/DeusExMachina#16]
I have the plugin enabled, and set to run only in vacation mode (no other modes are checked). It's turning my lights on even when I'm in home mode, though. Possibly relevant line from logs:

` DeusExMachinaII:deusStep(): run in state 1, modebits=16, currentMode=1,`

Don't know if it matters that I'm running the most current beta version, 1.7.891.

**Comment by toggledbits** [comment]
That message will be emitted any time the core loop is called, but isn't an indicator of whether or not it intends to change lighting. Be that as it may, there are issues in the current released version that I have addressed in my latest development branch (not fully pushed here yet). I'm going to try to get this updated branch out before Christmas.

**Comment by 3rdStng** [comment]
Granted I am still running v2.3, but I think it may not be honoring the mode. I too have the plugin set to run in away or vacation mode. Trying to determine why the light right next to me was going off when I updated any scenes, I finally found the log entry. Device 36 is the light that kept turning off on my.

`50	01/02/17 22:29:54.409	luup_log:81: DeusExMachinaII::deusInit(): Version 2.3 (2016-08-20), starting up... <0x76795520>
50	01/02/17 22:29:54.410	luup_log:81: DeusExMachinaII::deusEnable(): enabling... <0x76795520>
50	01/02/17 22:29:54.410	luup_log:81: DeusExMachinaII::deusStep(): wakeup, stamp 1483424994 <0x76795520>
50	01/02/17 22:29:54.414	luup_log:81: DeusExMachinaII:deusStep(): run in state 1, modebits=20, currentMode=1, lightsout=1274, luup.sunset=1483491306, os.time=1483424994 <0x76795520>
50	01/02/17 22:29:54.414	luup_log:81: +++ longitude=<<REMOVED>>, latitude=<<REMOVED>>, timezone=-8, city=<<REMOVED>>, version=1.7.2414 <0x76795520>
50	01/02/17 22:29:54.419	luup_log:81: DeusExMachinaII::deusStep(): Current mode bit 0x2 not in set 0x14 <0x76795520>
50	01/02/17 22:29:54.420	luup_log:81: DeusExMachinaII::deusStep(): lights out time <0x76795520>
50	01/02/17 22:29:54.420	luup_log:81: DeusExMachinaII::deusStep(): running off cycle <0x76795520>
06	01/02/17 22:29:54.420	Device_Variable::m_szValue_set device: 81 service: urn:toggledbits-com:serviceId:DeusExMachinaII1 variable: State was: 1 now: 3 #hooks: 0 upnp: 0 skip: 0 v:0x131ad50/NONE duplicate:0 <0x76795520>
08	01/02/17 22:29:54.421	JobHandler_LuaUPnP::HandleActionRequest device: 36 service: urn:upnp-org:serviceId:Dimming1 action: SetLoadLevelTarget <0x76795520>
08	01/02/17 22:29:54.422	JobHandler_LuaUPnP::HandleActionRequest argument newLoadlevelTarget=0 <0x76795520>
06	01/02/17 22:29:54.422	Device_Variable::m_szValue_set device: 36 service: urn:upnp-org:serviceId:Dimming1 variable: LoadLevelTarget was: 100 now: 0 #hooks: 0 upnp: 0 skip: 0 v:0x120a320/NONE duplicate:0 <0x76795520>
06	01/02/17 22:29:54.423	Device_Variable::m_szValue_set device: 36 service: urn:upnp-org:serviceId:SwitchPower1 variable: Target was: 1 now: 0 #hooks: 0 upnp: 0 skip: 0 v:0x11a1138/NONE duplicate:0 <0x76795520>
50	01/02/17 22:29:54.424	luup_log:81: DeusExMachinaII::turnOffLight(): set 36 to OFF; 0 devices still on. <0x76795520>
06	01/02/17 22:29:54.425	Device_Variable::m_szValue_set device: 81 service: urn:toggledbits-com:serviceId:DeusExMachinaII1 variable: State was: 3 now: 1 #hooks: 0 upnp: 0 skip: 0 v:0x131ad50/NONE duplicate:0 <0x76795520>
50	01/02/17 22:29:54.425	luup_log:81: DeusExMachina::deusStep(): all lights out; waiting for next sunset in 66468 <0x76795520>`
