### ISSUE TITLE
Request: allow setting of cycle time on a per-device/scene basis

### ISSUE THREAD

**Issue by doctorkb** [toggledbits/DeusExMachina#17]
As a user, I'd like to be able to set different cycle times for each device / scene so that I can control for how long a room is lit.

Scenario: I have several rooms under DEM control when I'm away.  Some of them are bathrooms (usually occupied for 5-10 minutes, then unoccupied for a while), others are living spaces (usually occupied for 30-60+ minutes), and others still are transition spaces (hallways, stairways, etc.), usually occupied for 30-60 seconds.  It would be nice if DEM could have different settings for each of these groups - so the stairway lights are on for ~60 seconds, but the living room might be on for 60 minutes.

**Comment by toggledbits** [comment]
This has been added to the develop branch and will appear in the upcoming release.
