### ISSUE TITLE
No way to save configuration

### ISSUE THREAD

**Issue by jacksonj04** [toggledbits/DeusExMachina#2]
There doesn't seem to be a way to save the configuration of the plugin:

![screen shot 2015-05-13 at 12 43 29](https://cloud.githubusercontent.com/assets/619082/7609708/c191226a-f96d-11e4-8844-b42b3785651b.png)

Firmware: 1.7.583

**Comment by tony-park** [comment]
I've got the same issue here, which means that the plugin won't function. Please advise if there are any steps that need to be performed for these changes to stick

**Comment by ThisNerd** [comment]
Same here no save button, not even sure this thing works...

**Comment by toggledbits** [comment]
Everyone, the original author of this plugin has recently passed the repository on to me. I've fixed this bug (not saving config on UI7) and am shaking down everything for an update/re-launch.

**Comment by tony-park** [comment]
Thanks Patrick, that's great news

Tony
