### ISSUE TITLE
Force turn-off of lights at disable leaves "welcome home" users in the dark

### ISSUE THREAD

**Issue by toggledbits** [toggledbits/DeusExMachina#20]
From MCV forums user Thorden: Could the turning off of lights that DEMII has turned on be optional for selected lights? For instance: Lights in my hallway is turned on (based on ambient light level) when I unlock the front door and disarm the alarm system. But if the same light is turned on by DEMII, it will be turned off. Hard to control which of the events that control that specific light, my "Welcome home" scene, or DEMII. Right now, lights are turned off by DEMII when I get home, so it welcomes me with darkness...

**Comment by gsads** [comment]
First of all... thanks so much, toggledbits. Your work is greatly appreciated :-)
I agree with Thorden. When coming home, my PIN in the lock automatically turns my house mode to "Home" and turns on a few lights. 5 minutes later they are all turned off due to DEMII finishing up its job. It would be amazing to have DEMII immediately stop making any changes as soon as it is disabled (directly or via changing mode).

**Comment by toggledbits** [comment]
OK, I'll put this on the list. I agree, it's not very convenient, it's 
just the way it has always worked, so I've resisted changing it, because 
I'm sure somebody else likes it the way it is. :-)


On 3/24/2017 10:07 AM, gsads wrote:
>
> First of all... thanks so much, toggledbits. Your work is greatly 
> appreciated :-)
> I agree with Thorden. When coming home, my PIN in the lock 
> automatically turns my house mode to "Home" and turns on a few lights. 
> 5 minutes later they are all turned off due to DEMII finishing up its 
> job. It would be amazing to have DEMII immediately stop making any 
> changes as soon as it is disabled (directly or via changing mode).
>

---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by toggledbits** [comment]
This has been added to the develop branch and will be included in the upcoming maintenance release.

**Comment by gsads** [comment]
When do you think you will be rolling out the maintenance release? Alternatively, is there any way I can make the changes?
Thanks!

**Comment by toggledbits** [comment]
It's out! Been out. Check your config. You should be running on 2.5. If your version isn't that, do an update. Then check your DEMII configuration screen.
