### ISSUE TITLE
Version 2.5 "version text" not updated

### ISSUE THREAD

**Issue by doctorkb** [toggledbits/DeusExMachina#22]
D_DeusExMachinaII1_UI7.json - line 119 - still shows 2.4 with old date.

This appears to be the text displayed in the Device panel, resulting in a perception that the plugin hasn't been updated.

(Also, the auto-update in Vera doesn't seem to be grabbing the new version yet...)

**Comment by toggledbits** [comment]
It's not yet been released. Still in testing. Stay tuned.
