### ISSUE TITLE
Turn-on to dimming level not always honored

### ISSUE THREAD

**Issue by toggledbits** [toggledbits/DeusExMachina#25]
Inconsistently, but usually, version 2.6 has started turning lights fully on instead of at the configured dimming level. Reported by Thorden on MCV forums.

**Comment by toggledbits** [comment]
Resolves in release 2.7. This was related to a "fix" done for certain Fibaro and Qubino dimmers. Backed the change out; I'll have to come up with something else.

**Comment by Adamski74** [comment]
Den 15 jan. 2018 19:33 skrev "Patrick Rigney" <notifications@github.com>:
