### ISSUE TITLE
DeusExMachina II doesn't show in 1.7.3832 - but DuesExMachina does

### ISSUE THREAD

**Issue by JtwoA** [toggledbits/DeusExMachina#27]
DeusExMachina II doesn't show in 1.7.3832 - but DuesExMachina does.  Did the usual search by DeusExMachina II and zero returns.  Dropped the "II" and, boom, there's the old one.  Any thoughts?

**Comment by toggledbits** [comment]
Their search is garbage. Just search for Deus. I confirmed that works on mine.

**Comment by JtwoA** [comment]
Got it.  There's no spacing in the title which is why Vera missed it.
Got it installed, thanks very much!
