### ISSUE TITLE
Feature: Show level percentage in config

### ISSUE THREAD

**Issue by rrauenza** [toggledbits/DeusExMachina#28]
I have LED lights that need a very specific minimum level - would it be possible to show the percentage selected next to the slider?

**Comment by toggledbits** [comment]
Yes! I really like this idea.

**Comment by rrauenza** [comment]
Or also make it an editable box that updates with the slider?

**Comment by toggledbits** [comment]
Editing is a feature of later jQuery UI, but the version used by UI7 is old (1.9-era) and doesn't support it. I could implement it all by hand, but I'm not yet convinced it's worth it, as the range is small (so the slider is quick and efficient), and once configured, these settings have a tendancy to be left alone. At this stage, I'm also concerned across the board about the changes for UI8, as big things have been promised;threatened.

**Comment by toggledbits** [comment]
The display of value is now in the "stable" release branch. It can be installed on ALTUI via the AltAppStore (install the "0.stable" release), or by downloading [this file](https://raw.githubusercontent.com/toggledbits/DeusExMachina/stable/J_DeusExMachinaII1_UI7.js) (right-click and Save link as...,) and then uploading it to your Vera (use the *Apps > Develop apps > Luup files* uploader). Then, hard-refresh your browser (Ctrl-F5 for Chrome/Windows, Shift-F5 for Firefox/Windows, etc.).

**Comment by toggledbits** [comment]
This was released in 2.8.
