### ISSUE TITLE
Request for Stop Action enhancement

### ISSUE THREAD

**Issue by 3rdStng** [toggledbits/DeusExMachina#30]
I leverage the Turn Controlled Lights Off feature, and it ultimately works. What would be awesome though is if it would turn the controlled lights off as soon as the house mode changes. Right now there is about a 5-10 minute delay from when I get home and enter the house to when the controlled lights turn off. It's a little wife upsetting when she has manually turned on a controlled light after getting home and then DeusExMachinaII turns it off on her within that 5-10 minutes.

**Comment by toggledbits** [comment]
OK. I get this. You're right, it should be a good bit more responsive.

**Comment by toggledbits** [comment]
The stable branch version now has house mode detection assisted by Reactor (better) or the Housemodes plugin (acceptable). It will use either when installed, Reactor preferred if both are installed.

**Comment by toggledbits** [comment]
Further improved, Reactor's approach to house mode detection has been incorporated into DEMII, so installation of Reactor or House Modes Plugin is not required, and the (high) performance typical of Reactor with respect to house mode changes will be seen in DEMII.

**Comment by toggledbits** [comment]
Released in 2.9
