### ISSUE TITLE
Set Activation Time 1 hour before Sunset?

### ISSUE THREAD

**Issue by MountBiker** [toggledbits/DeusExMachina#34]
Is there anyway to set DeusExMachina to run one hour before sunset or any user defined amount of time before sunset?

Most people are using their light before sunset.

If not, seems like a missing capability.

Thanks

**Comment by toggledbits** [comment]
DEMII provides just basic automatic triggering internally. For more complex rules, set the plugin for manual activation, and use the `Activate` and `Deactivate` actions in scenes, Reactor activities, PLEG actions, Lua, etc.
