### ISSUE TITLE
DEMII "lights out" when running with PLEG

### ISSUE THREAD

**Issue by epross672** [toggledbits/DeusExMachina#35]
I am doing this:

Set the active period to "Manual Activation" as described above, and use the Activate and Deactivate actions to start and stop cycling, respectively. When deactivating with this method, lights will be progressively turned off to simulate the bedtime "lights out" behavior DEMII uses with automatic scheduling. These actions are part of the urn:toggledbits.com:serviceId:DeusExMachinaII1 service, and take no parameters.

like this:

luup.call_action("urn:toggledbits-com:serviceId:DeusExMachinaII1", "Activate", {}, _deviceNumber_)

But how do I set the "Light out" time"

This seems to only set DEMII to be on / off but never get the lights out time.

**Comment by toggledbits** [comment]
If you're set for manual activation, you have to both manually activate and deactivate.

**Comment by epross672** [comment]
Yep, I got that!

So, I set it to Activate when IsNight AND I'm not home.  I set it to Deactivate when IsDay and/or I'm home.  

So that it good.  But does that mean that activating puts it "Cycling" mode?  Does that mean it never goes into "Shut-off" mode?

**Comment by toggledbits** [comment]
Correct... everything is manual.

**Comment by toggledbits** [comment]
You could just enable/disable it, rather than activate/deactivate, if you want to preserve its native timing capabilities.

**Comment by epross672** [comment]
Sorry for the questions...

 What is the difference between setting SetEnabled to true or false versus Activate/Deactivate?

**Comment by toggledbits** [comment]
* Disabled: DEMII will not run at all
* Enabled with Manual Activation *off*: DEMII will start and stop based on the timing set in its options.
* Enabled with Manual Activation *on*: DEMII will start when activated, stop when deactivated. Activate/deactivate is by calling the actions or using the UI activate/deactivate switch.

**Comment by epross672** [comment]
Wait........... 

let me back up.

Right now, I have DEMII disabled.  I have PLEG setting it to Activate when it's night and Im not home.  I have PLEG set to Deactivate it when I am home or it's day time.  Are you saying that I also have to enable DEMII as well?  So I just need to enable it once and then the manual activate/deactivate just works?

And if I am doing manual activate/deactivate, there's no way to get it into shut-off mode, it just stays in cycle mode?  Also I donated some money just because this is awesome and I appreciate the work!

**Comment by toggledbits** [comment]
> Right now, I have DEMII disabled. I have PLEG setting it to Activate when it's night and Im not home. I have PLEG set to Deactivate it when I am home or it's day time. Are you saying that I also have to enable DEMII as well?

Yes. If you `Activate` but DEMII is disabled, nothing will happen. It will log this message in the Vera log stream: `Activate (devnum) action request ignored; disabled.` If it's disabled, its timing options don't work, and manual activation also doesn't work; it does nothing no matter what you do. It has to be enabled for it to be *allowed* to work. Once enabled, whether or not it cycling is determined by automatic or manual activation mode.

> So I just need to enable it once and then the manual activate/deactivate just works?

Well, I would not say it "just works." If you are in *manual activation* mode, then you have to run the `Activate` and `Deactivate` actions, so there is "work" you have to do. If you are **not** in manual activation, then its built-in timing options are in effect and you don't need to do anything.

> And if I am doing manual activate/deactivate, there's no way to get it into shut-off mode, it just stays in cycle mode?

No, that wouldn't be very useful behavior. Let's look at a full trip through all states. To start, it stays in *idle* mode (doing nothing) until you `Activate`. Once you activate it, it's in *cycling* mode and cycles lights. When you deactivate it (i.e. run the `Deactivate` action), it goes into *shutdown* (shut-off, as you call it) mode, turning off lights periodically until all managed lights are off, and then it goes back to *idle* mode, waiting for the next activation.

Thanks for the donation! Super-generous and much appreciated!

**Comment by epross672** [comment]
OK, that all makes sense.

What I was referring to was this:

`DEMII's cycle timing is controlled by a set of state variables. By default, DEMII's random cycling of lights occurs at randomly selected intervals between 300 seconds (5 minutes) and 1800 seconds (30 minutes), as determined by the MinCycleDelay and MaxCycleDelay variables. You may change these values to customize the cycling time for your application.

When DEMII is in its "lights out" (shut-off) mode, it uses a different set of shorter (by default) cycle times, to more closely imitate actual human behavior. The random interval for lights-out is between 60 seconds and 300 seconds (5 minutes), as determined by MinOffDelay and MaxOffDelay. These intervals could be kept short, particularly if DEMII is controlling a large number of lights.`

If I am using the manual actiate/decativate, then it's going to always use MinCycleDelay and MaxCycleDelay and never MinOffDelay/MaxOffDelay?

**Comment by toggledbits** [comment]
The timing of cycling and shutdown is not affected by whether activation/deactivation is manual or automatic.
